app:
  stop_signal: SIGSTOP
  build: images/nodejs
  ports:
    - 3000:3000
    - 3001:3001
  links:
    - db
  volumes:
    - ../:/app
db:
  image: mongo
  volumes:
    - ./store/db:/data/db
  ports:
    - 27017:27017
    - 28017:28017
