app:
  stop_signal: SIGSTOP
  build: images/nodejs
  ports:
    - 3000:3000
    - 3001:3001
  links:
    - cache
    - db
  volumes:
    - ../:/app
cache:
  image: memcached:1.4
  command: memcached -m 8
db:
  image: mongo
  volumes:
    - ./store/db:/data/db
